# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "tracks", :force => true do |t|
    t.column "itunes_track_id", :integer
    t.column "name",            :string,  :limit => 100
    t.column "artist",          :string,  :limit => 100
    t.column "album",           :string,  :limit => 100
    t.column "genre",           :string,  :limit => 100
    t.column "duration",        :integer
    t.column "useraccount_id",  :integer
  end

end
